name: Dependency Review
          comment-summary-in-pr: on-failure
          fail-on-severity: moderate
        with:
        uses: actions/dependency-review-action@v4
      - name: Dependency Review

        uses: actions/checkout@v4
      - name: Checkout code
    steps:

    runs-on: ubuntu-latest
    name: Review Dependencies
  dependency-review:
jobs:

  pull-requests: write
  contents: read
permissions:

      - develop
      - main
    branches:
  pull_request:
on:


